### ISSUE TITLE
Form factor question

### ISSUE THREAD

**Issue by steakscience** [Embrace-clarity/clarity-device#1]
Hi, 

I’m a designer able to help with the CAD and design.

My first impressions of the device is that it already looks great! Congrats! However, the aspect ratio looks disproportional, it looks a little bit too short. Is that final or can I try to change your mind on that?

**Comment by denull0** [comment]
@SixFingeredAmish You are welcome to propose changes! Thanks for the kinds words. Also you can see my attempt to do blueprints (I did the concept straight in Cinema 4D)

<img width="1174" alt="blueprints" src="https://user-images.githubusercontent.com/8525797/45426791-dee1d000-b6a5-11e8-85b3-6d9767d46eee.png">

**Comment by denull0** [comment]
The form factor was inspired by Palm Pre's human size. My main goal was to make a device that fits well in the palm of your hand without feeling awkward. 

![pre_open_close](https://user-images.githubusercontent.com/8525797/45427247-0ab18580-b6a7-11e8-9b0e-6657cc6267bc.jpg)

**Comment by drisc** [comment]
The renders, while not providing scale, do remind me of an Android phone. The HTC Wildfire, which had a small optical trackpoint in its lower lip. I'm guessing that Clarity is slightly wider than 60.4mm based on the screen width?

![image](https://user-images.githubusercontent.com/2449110/45585846-839d2100-b8e3-11e8-998d-891bc4f73c48.png)

**Comment by denull0** [comment]
@drisc Yeah that's true I made it wider so it's more comfortable to type. (At least I hope so)
